library(tidyverse)
library(dplyr)
library(vegan)

###Make matrices to use as input for Mantel tests

#AdmixtureGeographicDistances_AllTrees.txt contains four columns -> Populations (each four population tree), logGeographicDistance (log of the average geographic distance between each population pair within the population tree),
#f4_TreeMix (f4 statistic generated by TreeMix), and f4_poolfstat (f4 statistic generated by poolfstat). This list contains all four population trees.

#AdmixtureGeographicDistances_SigTrees.txt contains four columns -> Populations (each four population tree), logGeographicDistance (log of the average geographic distance between each population pair within the population tree),
#f4_TreeMix (f4 statistic generated by TreeMix), and f4_poolfstat (f4 statistic generated by poolfstat). This list contains the four population tress with a significant f4 statistic from TreeMix or poolfstat.

#Code to find f4_TreeMix matrices below, replace TreeMix with poolfstat to get f4_poolfstat matrices.

allf4_geographicdistances <- read.delim("AdmixtureGeographicDistances_AllTrees.txt", header = TRUE, sep = "\t")
allf4_geographicdistances <- allf4_geographicdistances$logGeographicDistance
allf4_geographicdistances <- as.numeric(unlist(allf4_geographicdistances))
allf4_geographicdistances_matrix <- outer(allf4_geographicdistances, allf4_geographicdistances, FUN = "-")
allf4_geographicdistances_matrix <- abs(allf4_geographicdistances_matrix)
write.table(allf4_geographicdistances_matrix, file = "Allf4Tests.MantelTestInput_GeographicDistance.txt", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)

allf4_admixturedistances <- read.delim("AdmixtureGeographicDistances_AllTrees.txt", header = TRUE, sep = "\t")
allf4_admixturedistances <- allf4_admixturedistances$f4_Treemix
allf4_admixturedistances <- as.numeric(unlist(allf4_admixturedistances))
allf4_admixturedistances_matrix <- outer(allf4_admixturedistances, allf4_admixturedistances, FUN = "-")
allf4_admixturedistances_matrix <- abs(allf4_admixturedistances_matrix)
write.table(allf4_admixturedistances_matrix, file = "Allf4Tests.MantelTestInput_AdmixtureDistance_Treemix.txt", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)

sigf4_geographicdistances <- read.delim("AdmixtureGeographicDistances_SigTrees.txt", header = TRUE, sep = "\t")
sigf4_geographicdistances <- sigf4_geographicdistances$logGeographicDistance
sigf4_geographicdistances <- as.numeric(unlist(sigf4_geographicdistances))
sigf4_geographicdistances_matrix <- outer(sigf4_geographicdistances, sigf4_geographicdistances, FUN = "-")
sigf4_geographicdistances_matrix <- abs(sigf4_geographicdistances_matrix)
write.table(sigf4_geographicdistances_matrix, file = "Sigf4Tests.MantelTestInput_GeographicDistance.txt", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)

sigf4_admixturedistances <- read.delim("AdmixtureGeographicDistances_SigTrees.txt", header = TRUE, sep = "\t")
sigf4_admixturedistances <- sigf4_admixturedistances$f4_Treemix
sigf4_admixturedistances <- as.numeric(unlist(sigf4_admixturedistances))
sigf4_admixturedistances_matrix <- outer(sigf4_admixturedistances, sigf4_admixturedistances, FUN = "-")
sigf4_admixturedistances_matrix <- abs(sigf4_admixturedistances_matrix)
write.table(sigf4_admixturedistances_matrix, file = "Sigf4Tests.MantelTestInput_AdmixtureDistance_Treemix.txt", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)


###Mantel tests
##Is signal of admixture (f4 statistic) correlated with average geographic distance between populations? -> Mantel test, Z-score from f4 test (normalized f4 value) vs. log-transformed geographic distances (average geographic distance between the four populations involved in each f4 test)

mantel(allf4_admixturedistances_matrix, allf4_geographicdistances_matrix, method = "pearson", permutations = 1000, parallel = 1)

mantel(sigf4_admixturedistances_matrix, sigf4_geographicdistances_matrix, method = "pearson", permutations = 1000, parallel = 1)

##Is there a signal of isolation by distance (IBD)? -> Mantel test, linearized FST (FST/(1-FST) vs. log-transformed geographic distance
#Matrices made by hand for these Mantel tests in Excel
#Code for all populations Mantel test below replace all with Baltic or North to run Mantel tests for those population subsets.

allpops_geneticmatrix <- read.csv("Genetic Matrix File Name")
allpops_geographicmatrix <- read.csv("Geographic Matrix File Name")
mantel(allpops_genetic_matrix, allpops_geographic_matrix, method = "pearson", permutations = 1000, parallel = 1)